### ISSUE TITLE
Tracking issue for log evaluation

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#150]
This is the tracking issue for the [evaluation](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-16-log/5185/50) performed by the libs team this week:

* [x]  [#[macro_use(info)] raise error: macro undefined: 'log!'](https://github.com/rust-lang-nursery/log/issues/54)
* [x] [Link to logging sinks other than env_logger in the README/crate docs](https://github.com/rust-lang-nursery/log/issues/115)
* [x] [Support construction of `LogRecord`s and `LogMetadata`](https://github.com/rust-lang-nursery/log/issues/116)
* [x] [Remove logger shutdown](https://github.com/rust-lang-nursery/log/issues/117)
* [x] [Implement Debug for LogMetadata, LogRecord](https://github.com/rust-lang-nursery/log/issues/118)
* [x] [FromStr impls for LogLevel, LogLevelFilter use () as error type](https://github.com/rust-lang-nursery/log/issues/119)
* [x] [Use env_logger instead of my_logger in doc example](https://github.com/rust-lang-nursery/log/issues/120)
* [x] [Crate docs should mention the logging levels and corresponding macros](https://github.com/rust-lang-nursery/log/issues/121)
* [x] [Add example for log! macro](https://github.com/rust-lang-nursery/log/issues/122)
* [x] [Document `max_level_*`, `release_max_level_*` features in crate docs](https://github.com/rust-lang-nursery/log/issues/123)
* [x] [Add examples to debug!, error!, info!, trace!, warn!](https://github.com/rust-lang-nursery/log/issues/124)
* [x] [Expand log! docs for `max_level_*`](https://github.com/rust-lang-nursery/log/issues/125)
* [x] [Add example for second log_enabled! pattern variant](https://github.com/rust-lang-nursery/log/issues/126)
* [x] [LogLocation doc improvements](https://github.com/rust-lang-nursery/log/issues/127)
* [x] [LogMetadata doc improvements](https://github.com/rust-lang-nursery/log/issues/128)
* [x] [LogRecord doc improvements](https://github.com/rust-lang-nursery/log/issues/129)
* [x] [SetLoggerError doc improvements](https://github.com/rust-lang-nursery/log/issues/130)
* [x] [ShutdownLoggerError doc improvements](https://github.com/rust-lang-nursery/log/issues/131)
* [x] [LogLevel doc improvements](https://github.com/rust-lang-nursery/log/issues/132)
* [x] [LogLevelFilter doc improvements](https://github.com/rust-lang-nursery/log/issues/133)
* [x] [max_log_level doc improvements](https://github.com/rust-lang-nursery/log/issues/134)
* [x] [set_logger doc improvements](https://github.com/rust-lang-nursery/log/issues/135)
* [x] [set_logger_raw doc improvements](https://github.com/rust-lang-nursery/log/issues/136)
* [x] [Linkify crate doc description ](https://github.com/rust-lang-nursery/log/issues/137)
* [x] [Add CI badges to Cargo.toml ](https://github.com/rust-lang-nursery/log/issues/138)
* [x] [Update Cargo.toml documentation link to docs.rs ](https://github.com/rust-lang-nursery/log/issues/139)
* [x] [Add keywords to Cargo.toml ](https://github.com/rust-lang-nursery/log/issues/140)
* [x] [Change html_root_url to https://docs.rs/$crate/$version ](https://github.com/rust-lang-nursery/log/issues/141)
* [x] [Reduce "stuttering" in types ](https://github.com/rust-lang-nursery/log/issues/142)
* [x] [Add serde impls for LogLevel/LogLevelFilter ](https://github.com/rust-lang-nursery/log/issues/143)
* [x] [Implement common traits for more types ](https://github.com/rust-lang-nursery/log/issues/144)
* [x] [Remove env_logger from this repository ](https://github.com/rust-lang-nursery/log/issues/145)
* [x] [Change set_logger to panic on error ](https://github.com/rust-lang-nursery/log/issues/146)
* [x] [Consider changing the default enabled log levels ](https://github.com/rust-lang-nursery/log/issues/147)
* [x] [Ensure 0.3 works with the next major release ](https://github.com/rust-lang-nursery/log/issues/148)
* [ ] [Structured Logging ](https://github.com/rust-lang-nursery/log/issues/149)
- [x] [Standardize on capitalization of log levels](https://github.com/rust-lang-nursery/log/issues/183)
* [ ] Bump version to 1.0 (after all else)

**Comment by meven** [comment]
Could we make `rust fmt` mandatory for this crate ?

**Comment by dtolnay** [comment]
@meven let's have that discussion in a separate issue. This issue is about the libz blitz evaluation. I opened #182.

**Comment by dtolnay** [comment]
Closing because this is no longer useful as a tracking issue -- the only remaining item is structured logging which is being tracked in #149. If anyone would like to raise an additional 1.0 blocker, please open a new issue for it.
